// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_home_screen_screen_init(void)
{
    ui_home_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_home_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_home_screen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "0");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_bebas150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_home_screen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 75);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "km/h");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_bebas15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_controller_battery_icon = lv_img_create(ui_home_screen);
    lv_img_set_src(ui_controller_battery_icon, &ui_img_battery_icon_png);
    lv_obj_set_width(ui_controller_battery_icon, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_controller_battery_icon, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_controller_battery_icon, 75);
    lv_obj_set_y(ui_controller_battery_icon, -115);
    lv_obj_set_align(ui_controller_battery_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_controller_battery_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_controller_battery_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_controller_battery_icon, 250);

    ui_controller_battery_text = lv_label_create(ui_controller_battery_icon);
    lv_obj_set_width(ui_controller_battery_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_controller_battery_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_controller_battery_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_controller_battery_text, "0");
    lv_obj_set_style_text_color(ui_controller_battery_text, lv_color_hex(0x232222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_controller_battery_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_controller_battery_text, &ui_font_bebas20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_no_connection_icon = lv_img_create(ui_home_screen);
    lv_img_set_src(ui_no_connection_icon, &ui_img_no_connection_png);
    lv_obj_set_width(ui_no_connection_icon, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_no_connection_icon, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_no_connection_icon, 30);
    lv_obj_set_y(ui_no_connection_icon, -115);
    lv_obj_set_align(ui_no_connection_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_no_connection_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_no_connection_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_no_connection_icon, 180);

    ui_Container1 = lv_obj_create(ui_home_screen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 100);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 120);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -20);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "TRIP:");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_bebas20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tripkm = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_tripkm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tripkm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tripkm, 15);
    lv_obj_set_y(ui_tripkm, 0);
    lv_obj_set_align(ui_tripkm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tripkm, "0.0");
    lv_obj_set_style_text_font(ui_tripkm, &ui_font_bebas20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_skate_battery_icon1 = lv_img_create(ui_home_screen);
    lv_img_set_src(ui_skate_battery_icon1, &ui_img_battery_icon_png);
    lv_obj_set_width(ui_skate_battery_icon1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_skate_battery_icon1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_skate_battery_icon1, -75);
    lv_obj_set_y(ui_skate_battery_icon1, -115);
    lv_obj_set_align(ui_skate_battery_icon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_skate_battery_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_skate_battery_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_skate_battery_icon1, 250);

    ui_skate_battery_text = lv_label_create(ui_skate_battery_icon1);
    lv_obj_set_width(ui_skate_battery_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_skate_battery_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_skate_battery_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_skate_battery_text, "0");
    lv_obj_set_style_text_color(ui_skate_battery_text, lv_color_hex(0x232222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_skate_battery_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_skate_battery_text, &ui_font_bebas20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
