// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_home_screen
void ui_home_screen_screen_init(void);
extern lv_obj_t * ui_home_screen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_controller_battery_icon;
extern lv_obj_t * ui_controller_battery_text;
extern lv_obj_t * ui_no_connection_icon;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_tripkm;
extern lv_obj_t * ui_skate_battery_icon1;
extern lv_obj_t * ui_skate_battery_text;
// CUSTOM VARIABLES

// SCREEN: ui_shutdown_screen
void ui_shutdown_screen_screen_init(void);
extern lv_obj_t * ui_shutdown_screen;
extern lv_obj_t * ui_shutdown;
extern lv_obj_t * ui_Bar4;
// CUSTOM VARIABLES

// SCREEN: ui_splash_screen
void ui_splash_screen_screen_init(void);
extern lv_obj_t * ui_splash_screen;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_battery_icon_png);    // assets/battery_icon.png
LV_IMG_DECLARE(ui_img_no_connection_png);    // assets/no_connection.png
LV_IMG_DECLARE(ui_img_gb_png);    // assets/GB.png

// FONTS
LV_FONT_DECLARE(ui_font_bebas150);
LV_FONT_DECLARE(ui_font_bebas15);
LV_FONT_DECLARE(ui_font_bebas35);
LV_FONT_DECLARE(ui_font_bebas20);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
