// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_home_screen
void ui_home_screen_screen_init(void);
lv_obj_t * ui_home_screen;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_controller_battery_icon;
lv_obj_t * ui_controller_battery_text;
lv_obj_t * ui_no_connection_icon;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_tripkm;
lv_obj_t * ui_skate_battery_icon1;
lv_obj_t * ui_skate_battery_text;
// CUSTOM VARIABLES

// SCREEN: ui_shutdown_screen
void ui_shutdown_screen_screen_init(void);
lv_obj_t * ui_shutdown_screen;
lv_obj_t * ui_shutdown;
lv_obj_t * ui_Bar4;
// CUSTOM VARIABLES

// SCREEN: ui_splash_screen
void ui_splash_screen_screen_init(void);
lv_obj_t * ui_splash_screen;
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_home_screen_screen_init();
    ui_shutdown_screen_screen_init();
    ui_splash_screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_home_screen);
}
